import {eventType} from './eventType'
import {artistType} from './artistType'
import {venueType} from './venueType'
import {dataType} from './dataType'
import { newsType } from './newsType'
import { teamType } from './teamType'
import { sponsorType } from './sponsorType'
import { playlist } from './playListType'
import { video } from './videoType'
import { aboutType } from './aboutType'
export const schemaTypes = [artistType, eventType, venueType, dataType, newsType, teamType, sponsorType, playlist, video, aboutType]